controller_url = "http://127.0.0.1:7021"
orchestrators = [
    { domain_id = "domain-1", orchestrator_url="http://127.0.0.1:7011" }
]
resources = [
    { resource_provider_id = "http-ingress-1",  resource_class_type = "http-ingress", output_callback_declarations = ["new_request"], resource_configuration_url = "http:127.0.0.1:7033" }
]