node_id = "fda6ce79-46df-4f96-a0d2-456f720f606c"
agent_url = "http://localhost:7001"
invocation_url = "http://localhost:7002"
peers = [
    {id = "fda6ce79-46df-4f96-a0d2-456f720f606c", invocation_url="http://localhost:7002" }
]