[package]
name = "edgeless_node"
version = "0.1.0"
authors = ["Raphael Hetzel <hetzel@in.tum.de"]
edition = "2021"

[lib]
name = "edgeless_node"
path = "src/lib.rs"

[[bin]]
name = "edgeless_node_d"
path = "src/bin/edgeless_node_d.rs"

[features]
inabox = ["dep:edgeless_bal", "dep:edgeless_con", "dep:edgeless_orc"]

[dependencies]
log = "0.4"
env_logger = "0.10"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
uuid = {version= "1.3", features = ["v4", "serde"] }
async-trait = "0.1"
wasmtime = {version = "10", features=["component-model", "wat"]}
wasmtime-wasi = { version = "10" }
serde = "1.0"
clap = { version = "4.3", features=["derive"] }
toml = "0.7"
edgeless_api = {path = "../edgeless_api", features = ["grpc_impl"]}
edgeless_dataplane = {path = "../edgeless_dataplane" }
edgeless_bal = {path = "../edgeless_bal", optional = true}
edgeless_con = {path = "../edgeless_con", optional = true}
edgeless_orc = {path = "../edgeless_orc", optional = true}