[package]
name = "edgeless_con"
version = "0.1.0"
authors = ["Raphael Hetzel <hetzel@in.tum.de"]
edition = "2021"

[lib]
name = "edgeless_con"
path = "src/lib.rs"

[[bin]]
name = "edgeless_con_d"
path = "src/bin/edgeless_con_d.rs"